global LPM_renderAPI
global LPM_NetworkPlugins=#()
global LPM_Fun
global LPM_Root
global LPM_treeview_rollout
global LPM_RenderRo
global LPM_multiCameraRo
global LPM_RenderPass
global LPM_hardwareRender
global LPM_render
global LPM_Data
global LPM_Render
global atmRollout
global objectSetProps
global lightSetProps
global commonRollout
global LPM_activePass
global LPM_LoadingPreset
global LPM_Operators

global LPM_activeElement

global SelectLayarRoll
global doubleClick

global LPM_oldRenderSettings
global LPM_oldRenderSettingsNew
global LPM_renderer_closed

global LPM_ObjSetPropsBuff
global LPM_LightSetPropsBuff
global LPMPassSelectRoll

global LPM_SMTDSettings 				-- Dabelow
global LPM_NukeAPI 						-- Dabelow
global LPM_RenderDispatchThePass 		-- Dabelow Vray5 / Render Dispatch ( future renderer compatable )
global LPM_RenderDispatchAction 		-- Dabelow Vray5 / Render Dispatch ( future renderer compatable )
global LPM_RenderDispatchRestoreData 	-- Dabelow Vray5 / Render Dispatch ( future renderer compatable )
global LPM_OperatorData 				-- Dabelow 

global iconPath = LPM_Dir + "icons/"
global BackColor
global FontColor
